// Turns the renderer's compiled stylesheet into a TypeScript module, so Workers can import it
// (wrangler bundles .ts but has no CSS loader). Run by the root `pnpm build:css` after
// `@asksite/renderer`'s build:css. Output: src/generated.ts (gitignored).
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";

const css = readFileSync(new URL("../../renderer/styles/site.css", import.meta.url), "utf8");
if (css.length === 0) throw new Error("packages/renderer/styles/site.css is empty; run the renderer build:css first");
const sha256 = createHash("sha256").update(css, "utf8").digest("hex");

writeFileSync(
  new URL("../src/generated.ts", import.meta.url),
  `// Generated by packages/site-css/scripts/build.ts. Do not edit.\n` +
    `export const SITE_CSS: string = ${JSON.stringify(css)};\n` +
    `export const SITE_CSS_SHA256: string = ${JSON.stringify(sha256)};\n`,
);
console.log(`wrote packages/site-css/src/generated.ts (${css.length} bytes, sha256 ${sha256})`);
