// Turns the renderer's compiled stylesheets into a TypeScript module, so Workers can import them
// (wrangler bundles .ts but has no CSS loader). Run by the root `pnpm build:css` after
// `@asksite/renderer`'s build:css. Output: src/generated.ts (gitignored).
// A design uses its own sheet when packages/renderer/styles/sheets/<id>.css exists, otherwise the
// baseline sheet (A12). Identical sheets are written once, so designs that share a sheet share one object.
import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { DESIGN_IDS } from "@asksite/site-schema";

const styles = new URL("../../renderer/styles/", import.meta.url);
const sheetOf = (id: string) => (existsSync(new URL(`sheets/${id}.css`, styles)) ? id : "baseline");

const consts = new Map<string, { name: string; css: string }>(); // by sha256
const designs = DESIGN_IDS.map((id) => {
  const file = new URL(`out/${sheetOf(id)}.css`, styles);
  const css = readFileSync(file, "utf8");
  if (css.length === 0) throw new Error(`${file.pathname} is empty; run the renderer build:css first`);
  const sha256 = createHash("sha256").update(css, "utf8").digest("hex");
  const shared = consts.get(sha256) ?? { name: sheetOf(id).toUpperCase(), css };
  consts.set(sha256, shared);
  return { id, name: shared.name };
});

const type = "{ readonly css: string; readonly sha256: string }";
writeFileSync(
  new URL("../src/generated.ts", import.meta.url),
  `// Generated by packages/site-css/scripts/build.ts. Do not edit.\n` +
    `import type { DesignId } from "@asksite/site-schema";\n\n` +
    [...consts].map(([sha256, { name, css }]) => `const ${name}: ${type} = Object.freeze({ css: ${JSON.stringify(css)}, sha256: ${JSON.stringify(sha256)} });\n`).join("") +
    `\nexport const DESIGN_CSS: Readonly<Record<DesignId, ${type}>> = Object.freeze({ ${designs.map(({ id, name }) => `${id}: ${name}`).join(", ")} });\n\n` +
    `/** @deprecated Use DESIGN_CSS. The impact sheet, kept until Plans 2B, 3 and 4 have merged (A12-R). */\n` +
    `export const SITE_CSS: string = DESIGN_CSS.impact.css;\n` +
    `/** @deprecated Use DESIGN_CSS. The impact sheet's SHA-256, kept until Plans 2B, 3 and 4 have merged (A12-R). */\n` +
    `export const SITE_CSS_SHA256: string = DESIGN_CSS.impact.sha256;\n`,
);
for (const { id, name } of designs) console.log(`wrote DESIGN_CSS.${id} (${name})`);
console.log(`wrote packages/site-css/src/generated.ts (${consts.size} distinct sheet${consts.size === 1 ? "" : "s"})`);
